### PR TITLE
Fix: fail tests if before/after hooks failed to run

### LINKED ISSUE #5: `new Polly` errors not caught
### Problem

I am observing that `new Polly(/* ... */)` errors in setup-polly-jest aren't caught here:

https://github.com/gribnoysup/setup-polly-jest/blob/8c0acedca7f84a788f80974460893605f335a946/src/setupJasmine.js#L101

Instead, an error occurs when `pollyContext.polly.stop()` is called: `pollyContext.polly` is null:

```
  console.error jest/setup.js:95
    TypeError: Cannot read property 'stop' of null
        at Object.<anonymous> (/Users/swashcap/project/node_modules/setup-polly-jest/lib/setupJasmine.js:153:38)
        at Generator.next (<anonymous>)
        at asyncGeneratorStep (/Users/swashcap/project/node_modules/setup-polly-jest/lib/setupJasmine.js:8:103)
        at _next (/Users/swashcap/project/node_modules/setup-polly-jest/lib/setupJasmine.js:10:194)
        at /Users/swashcap/project/node_modules/setup-polly-jest/lib/setupJasmine.js:10:364
        at new Promise (<anonymous>)
        at Object.<anonymous> (/Users/swashcap/project/node_modules/setup-polly-jest/lib/setupJasmine.js:10:97)
        at Object.after (/Users/swashcap/project/node_modules/setup-polly-jest/lib/setupJasmine.js:161:25)
        at resolve (/Users/swashcap/project/node_modules/jest-jasmine2/build/queueRunner.js:43:12)
        at new Promise (<anonymous>)
        at mapper (/Users/swashcap/project/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
        at promise.then (/Users/swashcap/project/node_modules/jest-jasmine2/build/queueRunner.js:73:41)
        at process._tickCallback (internal/process/next_tick.js:68:7)

```

### Versions

* setup-polly-jest: `setup-polly-jest@0.5.2`
* Polly: `@pollyjs/core@2.6.2`
* npm: `6.9.0`
* Node.js: `10.16.0`

### PR DESCRIPTION
**Pull request by gribnoysup**
- Fail tests in before/after hooks if something goes wrong with Polly
- Update polly in tests: rewrite tests to use adapter-node-http adapter instead of adapter-fetch
- Use async-to-promises instead of regenerator-runtime when building the lib

### CODE REVIEW

File: src/setupJasmine.js [hunk 1]
```diff
@@ -80,34 +81,47 @@ function createTestFnProxy(Polly, fn, jasmineEnv) {
...
+              recordingName = recordingName.replace(
+                `${topSuite.description}/`,
+                ''
+              );
+            }
+
+            pollyContext.polly = new Polly(recordingName, pollyContext.options);
+          }
+        } catch (error) {
+          // If something went wrong while trying to create new polly
```
Comment (swashcap) [inline src/setupJasmine.js]: :+1:
